all: build clean

first_install:
	pip install -r requirements.txt
	pyinstaller --onefile import_photos.py

build:
	pyinstaller --onefile import_photos.py

clean:
	rm -rf build/
	rm -rf dist/
	rm -f import_photos.spec
